### ISSUE TITLE
Unloading modules errors silently

### ISSUE THREAD

**Issue by RyanSquared** [hashbang/irc-bot#11]
Modules end up getting re-added, without being removed. Exponentially grows bigger.

>11:41 <[]> Reloading at request of KellerFuchs
11:41 <[]> Reloading at request of KellerFuchs
11:41 <[]> Reloading at request of KellerFuchs
11:41 <[]> Reloading at request of KellerFuchs
11:41 <[]> Reloading at request of KellerFuchs
11:41 <[]> Reloading at request of KellerFuchs
11:41 <[]> Reloading at request of KellerFuchs
11:41 <[]> Reloading at request of KellerFuchs
11:41 <[]> Reloading at request of KellerFuchs
11:41 <[]> Reloading at request of KellerFuchs
11:41 <[]> Reloading at request of KellerFuchs
11:41 <[]> Reloading at request of KellerFuchs
11:41 <[]> Reloading at request of KellerFuchs
11:41 <[]> Reloading at request of KellerFuchs

**Comment by daurnimator** [comment]
Fixed.
