### ISSUE TITLE
v.gd presents CAPTCHAs to Tor users

### ISSUE THREAD

**Issue by KellerFuchs** [hashbang/irc-bot#4]
v.gd uses Cloudfare in a configuration which present CAPTCHAs to Tor users.
This is highly annoying (I'm not Google's image classification bot!), so it would be great to consider using another service.

**Comment by daurnimator** [comment]
Pick another one. I don't know which ones will have a captcha etc.

**Comment by KellerFuchs** [comment]
[tiny.cc](https://tiny.cc/) seems like a sane option.

Otherwise, [is.gd](https://www.is.gd/) seems not to spawn CAPTCHAs, despite using Cloudfare (they don't allow Tor users to create shortened URLs, but that's fine-ish).
