### ISSUE TITLE
Anchors are stripped off (shortened) URLs

### ISSUE THREAD

**Issue by KellerFuchs** [hashbang/irc-bot#7]
Given a URL like <https://github.com/hashbang/irc-bot/issues/7#issue-196239254>, the bot ignores the `#issue-196239254` anchor when shortening the link:

```
KellerFuchs │ https://github.com/hashbang/irc-bot/issues/7#issue-196239254
         [] │ KellerFuchs: Title "Anchors are stripped off (shortened) URLs · Issue #7 · hashbang/irc-bot · GitHub" Shortened < https://v.gd/TSWKaL >
```

As you can see, <https://v.gd/TSWKaL> points to <https://github.com/hashbang/irc-bot/issues/7>, not <https://github.com/hashbang/irc-bot/issues/7#issue-196239254>

**Comment by daurnimator** [comment]
Lots like an issue with v.gd. I guess we should just change to a different url shortener.
